imports:
  - { resource: ./application.yml }

services:
  Mooc.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ["@Mooc.Shared.ConnectionManager"]
